;;; nord-theme.el --- My Custom Nord Theme           -*- lexical-binding: t; -*-

;; Copyright (C) 2025  Trevor Arjeski

;; Author: Trevor Arjeski <tmarjeski@gmail.com>
;; Keywords:

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;;

;;; Code:

(eval-and-compile
  (require 'autothemer)

  (defun color-modify-hex (hex target percent)
    (autothemer-rgb-to-hex
     (color-blend (autothemer-hex-to-rgb target)
                  (autothemer-hex-to-rgb hex)
                  percent)))

  (defun color-lighten-hex (hex percent)
    (color-modify-hex hex "#FFFFFF" percent))

  (defun color-darken-hex (hex percent)
    (color-modify-hex hex "#000000" percent))

  (autothemer-deftheme
   nord "Nord theme with customizations"

   ((((class color) (min-colors #xFFFFFF)))

    ;; Palette

    (bg         "#2E3440")
    (bg-alt     "#272C36")
    (base0      "#191C25")
    (base1      "#242832")
    (base2      "#2C333F")
    (base3-alt  "#323945")              ; (color-lighten-hex "#2C333F" 0.03)
    (base3      "#373E4C")
    (base4      "#434C5E")
    (base5      "#4C566A")
    (base5-alt  "#555E71")              ; (color-lighten-hex "#4C566A" 0.05)
    (base5-alt2 "#79808F")              ; (color-lighten-hex "#4C566A" 0.25)
    (base6      "#9099AB")
    (base7      "#D8DEE9")
    (base8      "#F0F4FC")
    (fg         "#ECEFF4")
    (fg-alt     "#E5E9F0")

    (grey       base4)
    (red        "#BF616A")
    (orange     "#D08770")
    (green      "#A3BE8C")
    (teal       "#8FBCBB")
    (yellow     "#EBCB8B")
    (blue       "#81A1C1")
    (dark-blue  "#5E81AC")
    (magenta    "#B48EAD")
    (violet     "#5D80AE")
    (cyan       "#88C0D0")
    (dark-cyan  "#507681"))

   ((default (:background bg :foreground fg))
    (flyspell-duplicate (:underline (:style 'line :position 3 :color yellow)))
    (flyspell-incorrect (:underline (:style 'line :position 3 :color red)))
    (magit-blame-date (:foreground red)) (magit-blame-name nil)
    (magit-blame-hash (:foreground cyan)) (magit-blame-summary nil)
    (magit-blame-heading (:extend t :foreground orange :background base3))
    (magit-blame-dimmed (:weight 'normal :slant 'normal :inherit 'magit-dimmed))
    (magit-blame-margin
     (:weight 'normal :slant 'normal :inherit 'magit-blame-highlight))
    (magit-blame-highlight (:extend t :foreground fg :background base3))
    (magit-reflog-other (:foreground cyan))
    (magit-reflog-remote (:foreground cyan))
    (magit-reflog-cherry-pick (:foreground green))
    (magit-reflog-rebase (:foreground magenta))
    (magit-reflog-reset (:inherit 'error))
    (magit-reflog-checkout (:foreground blue))
    (magit-reflog-merge (:foreground green))
    (magit-reflog-amend (:foreground magenta))
    (magit-reflog-commit (:foreground green))
    (magit-bisect-bad (:foreground red))
    (magit-bisect-skip (:foreground orange))
    (magit-bisect-good (:foreground green))
    (magit-sequence-exec (:inherit 'magit-hash))
    (magit-sequence-onto (:inherit 'magit-sequence-done))
    (magit-sequence-done (:inherit 'magit-hash))
    (magit-sequence-drop (:foreground red))
    (magit-sequence-head (:foreground blue))
    (magit-sequence-part (:foreground orange))
    (magit-sequence-stop (:foreground green))
    (magit-sequence-pick (:inherit 'default))
    (magit-filename (:foreground violet))
    (magit-cherry-equivalent (:foreground violet))
    (magit-cherry-unmatched (:foreground cyan))
    (magit-signature-error (:inherit 'error))
    (magit-signature-revoked (:foreground magenta))
    (magit-signature-expired-key (:inherit 'magit-signature-expired))
    (magit-signature-expired (:foreground orange))
    (magit-signature-untrusted (:foreground yellow))
    (magit-signature-bad (:inherit 'error))
    (magit-signature-good (:inherit 'success))
    (magit-keyword-squash (:inherit 'font-lock-warning-face))
    (magit-keyword (:inherit 'font-lock-string-face))
    (magit-refname-pullreq (:inherit 'magit-refname))
    (magit-refname-wip (:inherit 'magit-refname))
    (magit-refname-stash (:inherit 'magit-refname))
    (magit-refname (:foreground dark-blue))
    (magit-head (:inherit 'magit-branch-local))
    (magit-branch-warning (:inherit 'warning))
    (magit-branch-upstream (:slant 'italic))
    (magit-branch-current (:foreground blue))
    (magit-branch-local (:foreground cyan))
    (magit-branch-remote-head (:box 1 :inherit 'magit-branch-remote))
    (magit-branch-remote (:foreground green))
    (magit-tag (:foreground yellow))
    (magit-hash (:foreground dark-blue))
    (magit-dimmed (:foreground fg-alt))
    (magit-header-line-key (:inherit 'font-lock-builtin-face))
    (magit-header-line (:inherit 'header-line))
    (magit-header-line-log-select (:inherit 'bold))
    (magit-log-date (:foreground blue))
    (magit-log-author (:foreground orange))
    (magit-log-graph (:foreground dark-blue))
    (which-func (:foreground blue))
    (magit-diffstat-removed (:foreground red))
    (magit-diffstat-added (:foreground green))
    (magit-diff-whitespace-warning (:inherit 'trailing-whitespace))
    (magit-diff-context-highlight (:extend t :foreground fg :background bg-alt))
    (magit-diff-their-highlight (:inherit 'magit-diff-added-highlight))
    (magit-diff-base-highlight
     (:weight 'bold :extend t :foreground orange :background base3))
    (magit-diff-our-highlight (:inherit 'magit-diff-removed-highlight))
    (magit-diff-removed-highlight
     (:weight 'bold :extend t :foreground red :background base3))
    (magit-diff-added-highlight
     (:weight 'bold :extend t :foreground green :background base4))
    (magit-diff-context (:extend t :foreground base6 :background bg))
    (magit-diff-their (:inherit 'magit-diff-added))
    (magit-diff-base (:extend t :foreground orange :background base3))
    (magit-diff-our (:inherit 'magit-diff-removed))
    (magit-diff-removed (:extend t :foreground red :background base3))
    (magit-diff-added (:extend t :foreground green :background base3))
    (magit-diff-conflict-heading (:inherit 'magit-diff-hunk-heading))
    (magit-diff-lines-boundary (:extend t :inherit 'magit-diff-lines-heading))
    (magit-diff-lines-heading (:extend t :foreground yellow :background red))
    (magit-diff-revision-summary-highlight
     (:inherit 'magit-diff-hunk-heading-highlight))
    (magit-diff-revision-summary (:inherit 'magit-diff-hunk-heading))
    (magit-diff-hunk-region (:extend t :inherit 'bold))
    (magit-diff-hunk-heading-selection
     (:extend t :foreground orange :inherit 'magit-diff-hunk-heading-highlight))
    (magit-diff-hunk-heading-highlight
     (:weight 'bold :extend t :foreground bg :background violet))
    (magit-diff-hunk-heading (:extend t :foreground bg :background base4))
    (magit-diff-file-heading-selection
     (:weight 'bold :extend t :foreground magenta :background dark-blue))
    (magit-diff-file-heading-highlight
     (:extend t :inherit 'magit-section-highlight))
    (magit-diff-file-heading (:weight 'bold :extend t :foreground fg))
    (smerge-refined-added (:inverse-video t :inherit 'diff-added))
    (smerge-refined-removed (:inverse-video t :inherit 'diff-removed))
    (smerge-refined-changed nil)
    (smerge-markers (:weight 'bold :extend t :foreground bg :background dark-blue))
    (smerge-base (:extend t :background base4))
    (smerge-lower (:extend t :background base4))
    (smerge-upper (:extend t :background base3))
    (git-commit-comment-action (:inherit 'bold))
    (git-commit-comment-file (:foreground violet))
    (git-commit-comment-heading (:foreground blue))
    (git-commit-comment-detached (:foreground orange))
    (git-commit-comment-branch-remote (:foreground green))
    (git-commit-comment-branch-local (:foreground magenta))
    (git-commit-trailer-value (:slant 'italic :foreground base6))
    (git-commit-trailer-token (:weight 'bold :slant 'italic :foreground base6))
    (git-commit-keyword (:slant 'italic :foreground cyan))
    (git-commit-nonempty-second-line (:inherit 'git-commit-overlong-summary))
    (git-commit-overlong-summary
     (:weight 'bold :slant 'italic :background base0 :inherit 'error))
    (git-commit-summary (:foreground green))
    (magit-mode-line-process-error (:inherit 'error))
    (magit-mode-line-process (:inherit 'mode-line-emphasis))
    (magit-process-ng (:inherit 'error))
    (magit-process-ok (:inherit 'success))
    (shell-highlight-undef-alias-face (:inherit 'font-lock-variable-name-face))
    (shell-highlight-undef-undefined-face (:inherit 'font-lock-warning-face))
    (shell-highlight-undef-defined-face (:inherit 'font-lock-function-name-face))
    (transient-mismatched-key (:box (:line-width 1 :color magenta)))
    (transient-nonstandard-key (:box (:line-width 1 :color teal)))
    (transient-unreachable-key (:weight 'normal :inherit ('shadow 'transient-key)))
    (transient-key-exit (:foreground fg :inherit 'transient-key))
    (transient-key-return (:foreground yellow :inherit 'transient-key))
    (transient-key-noop (:foreground base4 :inherit 'transient-key))
    (transient-key-stay (:foreground green :inherit 'transient-key))
    (transient-key (:inherit 'font-lock-builtin-face))
    (transient-delimiter (:inherit 'shadow))
    (transient-higher-level (:box (:line-width 1 :color bg-alt)))
    (transient-disabled-suffix (:weight 'bold :foreground base0 :background orange))
    (transient-enabled-suffix (:weight 'bold :foreground base0 :background green))
    (transient-active-infix (:inherit 'highlight))
    (transient-inapt-suffix (:slant 'italic :inherit 'shadow))
    (transient-unreachable (:inherit 'shadow))
    (transient-inactive-value (:inherit 'shadow))
    (transient-value (:weight 'bold :inherit 'font-lock-string-face))
    (transient-inactive-argument (:inherit 'shadow))
    (transient-argument (:weight 'bold :inherit 'font-lock-string-face))
    (transient-heading (:inherit 'font-lock-keyword-face))
    (magit-section-child-count nil)
    (magit-section-heading-selection (:weight 'bold :extend t :foreground orange))
    (magit-section-secondary-heading (:weight 'bold :extend t :foreground violet))
    (magit-section-heading (:weight 'bold :extend t :foreground blue))
    (magit-section-highlight (:extend t :background base3))
    (shortdoc-section (:inherit 'variable-pitch))
    (shortdoc-heading (:height 1.3 :weight 'bold :inherit 'variable-pitch))
    (aw-key-face (:inherit 'font-lock-builtin-face))
    (aw-mode-line-face (:inherit 'mode-line-buffer-id))
    (aw-background-face (:foreground base5))
    (aw-minibuffer-leading-char-face (:inherit 'aw-leading-char-face))
    (aw-leading-char-face (:foreground orange))
    (avy-goto-char-timer-face (:inherit 'highlight))
    (avy-background-face (:foreground dark-blue))
    (avy-lead-face (:weight 'bold :foreground bg :background cyan))
    (avy-lead-face-2 (:background dark-blue :inherit 'avy-lead-face))
    (avy-lead-face-1 (:background dark-cyan :inherit 'avy-lead-face))
    (avy-lead-face-0 (:background blue :inherit 'avy-lead-face))
    (corfu--cbar (:inherit ('corfu--bar 'corfu-current)))
    (corfu--bar (:foreground base6))
    (consult-separator (:foreground bg-alt))
    (consult-line-number-wrapped (:inherit 'font-lock-warning-face))
    (consult-line-number-prefix (:inherit 'line-number))
    (consult-buffer nil)
    (consult-bookmark (:inherit 'font-lock-constant-face))
    (consult-grep-context (:inherit 'shadow))
    (consult-file (:inherit 'font-lock-function-name-face))
    (consult-line-number (:inherit 'consult-key))
    (consult-key (:inherit 'font-lock-keyword-face))
    (consult-help (:inherit 'shadow))
    (consult-async-split (:inherit 'font-lock-negation-char-face))
    (consult-async-failed (:inherit 'error))
    (consult-async-finished (:inherit 'success))
    (consult-async-running (:inherit 'consult-narrow-indicator))
    (consult-narrow-indicator (:inherit 'warning))
    (consult-preview-insertion (:inherit 'region))
    (consult-preview-match (:inherit 'isearch))
    (consult-highlight-mark (:inherit 'consult-highlight-match))
    (consult-highlight-match (:inherit 'match))
    (consult-preview-line (:extend t :inherit 'consult-preview-insertion))
    (bookmark-face (:extend t :background base3))
    (bookmark-menu-bookmark (:weight 'bold))
    (gnus-server-offline (:weight 'bold :foreground yellow))
    (gnus-server-denied (:weight 'bold :foreground magenta))
    (gnus-server-closed (:slant 'italic :foreground cyan))
    (gnus-server-opened (:weight 'bold :foreground green))
    (gnus-server-cloud-host (:slant 'italic :inverse-video t :foreground green))
    (gnus-server-cloud (:weight 'bold :foreground green))
    (gnus-server-agent (:weight 'bold :foreground teal))
    (gnus-header-content (:inherit 'message-header-other))
    (gnus-header-name (:inherit 'message-header-name))
    (gnus-header-newsgroups (:inherit 'message-header-other))
    (gnus-header-subject (:inherit 'message-header-subject))
    (gnus-header-from (:inherit 'message-header-other))
    (gnus-header (:inherit 'variable-pitch-text))
    (gnus-signature (:foreground yellow))
    (gnus-button (:weight 'bold))
    (gnus-emphasis-highlight-words (:foreground yellow :background base0))
    (gnus-emphasis-strikethru (:strike-through t))
    (gnus-emphasis-underline-bold-italic
     (:weight 'bold :slant 'italic :underline t))
    (gnus-emphasis-bold-italic (:weight 'bold :slant 'italic))
    (gnus-emphasis-underline-italic (:slant 'italic :underline t))
    (gnus-emphasis-underline-bold (:weight 'bold :underline t))
    (gnus-emphasis-underline (:underline t))
    (gnus-emphasis-italic (:slant 'italic))
    (gnus-emphasis-bold (:weight 'bold))
    (mm-uu-extract (:extend t :foreground base7 :background base3))
    (shr-sliced-image (:underline nil :overline nil))
    (shr-mark (:foreground base0 :background yellow))
    (shr-code (:inherit 'fixed-pitch))
    (shr-h6 (:inherit 'default))
    (shr-h5 (:inherit 'default))
    (shr-h4 (:inherit 'default))
    (shr-h3 (:slant 'italic))
    (shr-h2 (:weight 'bold))
    (shr-h1 (:height 1.3 :weight 'bold))
    (shr-sup (:height 0.8))
    (shr-abbreviation (:underline (:style 'line :position 3) :inherit 'underline))
    (shr-selected-link (:background orange :inherit 'shr-link))
    (shr-link (:inherit 'link))
    (shr-strike-through (:strike-through t))
    (shr-text (:inherit 'variable-pitch-text))
    (orderless-match-face-3 (:weight 'bold :foreground yellow :background base3))
    (orderless-match-face-2 (:weight 'bold :foreground green :background base3))
    (orderless-match-face-1 (:weight 'bold :foreground magenta :background base3))
    (orderless-match-face-0 (:weight 'bold :foreground base7 :background base3))
    (diff-hl-reverted-hunk-highlight (:inverse-video t))
    (diff-hl-change (:foreground orange :background orange))
    (diff-hl-delete (:foreground red :background red))
    (diff-hl-insert (:foreground green :background green))
    (log-view-commit-body (:inherit 'font-lock-comment-face))
    (log-view-message (:weight 'bold :extend t))
    (log-view-file (:weight 'bold :extend t))
    (log-edit-unknown-header (:inherit 'font-lock-comment-face))
    (log-edit-header (:inherit 'font-lock-keyword-face))
    (log-edit-headers-separator (:height 0.1 :extend t :inverse-video t))
    (log-edit-summary (:inherit 'font-lock-function-name-face))
    (message-signature-separator (:weight 'bold))
    (message-mml (:slant 'italic :foreground dark-blue))
    (message-cited-text-4 (:foreground green))
    (message-cited-text-3 (:foreground green))
    (message-cited-text-2 (:foreground magenta))
    (message-cited-text-1 (:foreground violet))
    (message-separator (:foreground dark-blue))
    (message-header-xheader (:foreground base6))
    (message-header-name (:foreground green))
    (message-header-other (:foreground violet))
    (message-header-newsgroups (:foreground yellow))
    (message-header-subject (:weight 'bold :foreground blue))
    (message-header-cc (:foreground dark-blue :inherit 'message-header-to))
    (message-header-to (:weight 'bold :foreground blue))
    (dired-ignored (:foreground dark-blue))
    (dired-special (:inherit 'font-lock-variable-name-face))
    (dired-broken-symlink (:weight 'bold :foreground yellow :background orange))
    (dired-symlink (:weight 'bold :foreground cyan))
    (dired-directory (:foreground blue))
    (dired-set-id (:inherit 'font-lock-warning-face))
    (dired-perm-write (:underline t :foreground fg))
    (dired-warning (:foreground yellow))
    (dired-flagged (:foreground red))
    (dired-marked (:weight 'bold :inverse-video t :foreground magenta))
    (dired-mark (:weight 'bold :foreground orange))
    (dired-header (:weight 'bold :foreground blue))
    (epa-field-body (:slant 'italic :foreground teal))
    (epa-field-name (:weight 'bold :foreground teal))
    (epa-mark (:weight 'bold :foreground yellow))
    (epa-string (:foreground fg))
    (epa-validity-disabled (:slant 'italic :inverse-video t))
    (epa-validity-low (:slant 'italic))
    (epa-validity-medium (:slant 'italic :foreground teal))
    (epa-validity-high (:weight 'bold :foreground teal))
    (mm-command-output (:foreground green))
    (change-log-acknowledgment (:inherit 'font-lock-comment-face))
    (change-log-function (:inherit 'font-lock-variable-name-face))
    (change-log-conditionals (:inherit 'font-lock-variable-name-face))
    (change-log-list (:inherit 'font-lock-keyword-face))
    (change-log-file (:inherit 'font-lock-function-name-face))
    (change-log-email (:inherit 'font-lock-variable-name-face))
    (change-log-name (:inherit 'font-lock-constant-face))
    (change-log-date (:inherit 'font-lock-string-face))
    (vc-dir-status-ignored (:inherit 'shadow))
    (vc-dir-status-up-to-date (:inherit 'font-lock-builtin-face))
    (vc-dir-status-edited (:inherit 'font-lock-variable-name-face))
    (vc-dir-status-warning (:inherit 'font-lock-warning-face))
    (vc-dir-mark-indicator (:inherit 'font-lock-type-face))
    (vc-dir-file (:inherit 'font-lock-function-name-face))
    (vc-dir-directory (:inherit 'font-lock-comment-delimiter-face))
    (vc-dir-header-value (:inherit 'font-lock-variable-name-face))
    (vc-dir-header (:inherit 'font-lock-type-face))
    (diff-refine-added (:inverse-video t :inherit 'diff-added))
    (diff-refine-removed (:inverse-video t :inherit 'diff-removed))
    (diff-refine-changed (:inverse-video t :inherit 'diff-changed))
    (diff-error (:weight 'bold :foreground orange :background base0))
    (diff-nonexistent (:inherit 'diff-file-header))
    (diff-context (:extend t :foreground base7))
    (diff-function (:inherit 'diff-header))
    (diff-indicator-changed (:foreground green :inherit 'diff-changed))
    (diff-indicator-added (:foreground green :inherit 'diff-added))
    (diff-indicator-removed (:foreground red :inherit 'diff-removed))
    (diff-changed (:foreground violet))
    (diff-changed-unspecified (:extend t :background bg-alt :inherit 'diff-changed))
    (diff-added (:extend t :foreground green :inherit 'hl-line))
    (diff-removed (:extend t :foreground red :background base3))
    (diff-hunk-header (:foreground violet))
    (diff-index (:inherit 'diff-file-header))
    (diff-file-header (:extend t :foreground blue))
    (diff-header (:extend t :foreground cyan))
    (vc-git-log-edit-summary-max-warning (:inherit 'error))
    (vc-git-log-edit-summary-target-warning (:inherit 'warning))
    (rainbow-delimiters-depth-1-face (:foreground blue))
    (rainbow-delimiters-depth-2-face (:foreground magenta))
    (rainbow-delimiters-depth-3-face (:foreground green))
    (rainbow-delimiters-depth-4-face (:foreground violet))
    (rainbow-delimiters-depth-5-face (:foreground teal))
    (rainbow-delimiters-depth-6-face (:foreground blue))
    (rainbow-delimiters-depth-7-face (:foreground magenta))
    (rainbow-delimiters-depth-8-face (:foreground green))
    (rainbow-delimiters-depth-9-face (:foreground violet))
    (rainbow-delimiters-mismatched-face
     (:inherit 'rainbow-delimiters-unmatched-face))
    (rainbow-delimiters-unmatched-face
     (:weight 'bold :inverse-video t :foreground red))
    (rainbow-delimiters-base-error-face
     (:foreground red :inherit 'rainbow-delimiters-base-face))
    (rainbow-delimiters-base-face (:inherit 'default))
    (gnus-splash (:foreground base7))
    (gnus-summary-low-read (:foreground base7))
    (gnus-summary-high-read (:foreground fg))
    (gnus-summary-normal-read (:extend t :foreground fg))
    (gnus-summary-low-unread (:foreground green))
    (gnus-summary-high-unread (:foreground green))
    (gnus-summary-normal-unread (:extend t :foreground green :inherit 'bold))
    (gnus-summary-low-undownloaded
     (:slant 'italic :inherit 'gnus-summary-normal-undownloaded))
    (gnus-summary-high-undownloaded
     (:weight 'bold :inherit 'gnus-summary-normal-undownloaded))
    (gnus-summary-normal-undownloaded
     (:weight 'normal :extend t :foreground dark-cyan))
    (gnus-summary-low-ancient (:foreground base3 :inherit 'italic))
    (gnus-summary-high-ancient (:foreground dark-blue :inherit 'italic))
    (gnus-summary-normal-ancient (:extend t :foreground base5 :inherit 'italic))
    (gnus-summary-low-ticked (:foreground magenta))
    (gnus-summary-high-ticked (:foreground magenta))
    (gnus-summary-normal-ticked (:extend t :foreground magenta))
    (gnus-summary-cancelled (:extend t :strike-through t :foreground red))
    (gnus-summary-selected (:weight 'bold :extend t :foreground blue))
    (gnus-group-mail-low (:weight 'normal :inherit 'gnus-group-mail-1))
    (gnus-group-mail-low-empty (:inherit 'gnus-group-mail-1-empty))
    (gnus-group-mail-3 (:inherit 'gnus-group-mail-1))
    (gnus-group-mail-3-empty (:inherit 'gnus-group-mail-1-empty))
    (gnus-group-mail-2 (:inherit 'gnus-group-mail-1))
    (gnus-group-mail-2-empty (:inherit 'gnus-group-mail-1-empty))
    (gnus-group-mail-1 (:weight 'bold :foreground fg))
    (gnus-group-mail-1-empty (:foreground base5))
    (gnus-group-news-low (:foreground base5 :inherit 'gnus-group-mail-1))
    (gnus-group-news-low-empty (:weight 'normal :inherit 'gnus-group-news-low))
    (gnus-group-news-6 (:inherit 'gnus-group-news-1))
    (gnus-group-news-6-empty (:inherit 'gnus-group-news-1-empty))
    (gnus-group-news-5 (:inherit 'gnus-group-news-1))
    (gnus-group-news-5-empty (:inherit 'gnus-group-news-1-empty))
    (gnus-group-news-4 (:inherit 'gnus-group-news-1))
    (gnus-group-news-4-empty (:inherit 'gnus-group-news-1-empty))
    (gnus-group-news-3 (:inherit 'gnus-group-news-1))
    (gnus-group-news-3-empty (:inherit 'gnus-group-news-1-empty))
    (gnus-group-news-2 (:inherit 'gnus-group-news-1))
    (gnus-group-news-2-empty (:inherit 'gnus-group-news-1-empty))
    (gnus-group-news-1 (:inherit 'gnus-group-mail-1))
    (gnus-group-news-1-empty (:inherit 'gnus-group-mail-1-empty))
    (gnus-cite-11 (:foreground green))
    (gnus-cite-10 (:foreground yellow))
    (gnus-cite-9 (:foreground blue))
    (gnus-cite-8 (:foreground magenta))
    (gnus-cite-7 (:foreground green))
    (gnus-cite-6 (:foreground yellow))
    (gnus-cite-5 (:foreground blue))
    (gnus-cite-4 (:foreground magenta))
    (gnus-cite-3 (:foreground green))
    (gnus-cite-2 (:foreground yellow))
    (gnus-cite-1 (:foreground blue))
    (gnus-cite-attribution (:slant 'italic))
    (xref-match (:inherit 'match))
    (xref-line-number (:inherit 'compilation-line-number))
    (xref-file-header (:inherit 'compilation-info))
    (hexl-ascii-region (:box nil :foreground fg :background bg-alt))
    (hexl-address-region (:inherit 'header-line))
    (textsec-suspicious (:weight 'bold :foreground fg :background orange))
    (eww-valid-certificate (:weight 'bold :foreground green))
    (eww-invalid-certificate (:weight 'bold :foreground red))
    (eww-form-textarea (:box (:line-width 1) :foreground base0 :background base7))
    (eww-form-text (:box (:line-width 1) :foreground fg :background base4))
    (eww-form-select
     (:box (:line-width 2 :style 'released-button) :foreground base0 :background
           base7))
    (eww-form-checkbox
     (:box (:line-width 2 :style 'released-button) :foreground base0 :background
           base7))
    (eww-form-file
     (:box (:line-width 2 :style 'released-button) :foreground base0 :background
           base6))
    (eww-form-submit
     (:box (:line-width 2 :style 'released-button) :foreground base0 :background
           base6))
    (vtable (:inherit 'variable-pitch))
    (header-line-inactive (:inherit 'mode-line-inactive))
    (header-line-active (:inherit 'mode-line-active))
    (custom-group-subtitle (:foreground red))
    (custom-group-tag (:foreground violet))
    (custom-group-tag-1 (:foreground blue))
    (custom-face-tag (:inherit 'custom-variable-tag))
    (custom-visibility (:foreground blue))
    (custom-variable-button (:underline t :foreground green))
    (custom-variable-tag (:foreground magenta))
    (custom-variable-obsolete (:foreground base4 :background bg))
    (custom-comment-tag (:foreground base4))
    (custom-comment (:foreground fg :background base4))
    (custom-link (:inherit 'link))
    (custom-state (:foreground green :background base4))
    (custom-documentation nil)
    (custom-button-pressed-unraised
     (:box (:line-width 1 :style nil) :foreground bg :background violet))
    (custom-button-pressed
     (:box (:line-width 1 :style nil) :foreground bg :background blue))
    (custom-button-unraised
     (:box (:line-width 1 :style nil) :foreground violet :background bg))
    (custom-button-mouse
     (:box (:line-width 1 :style nil) :foreground bg :background blue))
    (custom-button
     (:box (:line-width 1 :style nil) :foreground blue :background bg))
    (custom-saved (:weight 'bold :foreground green :background base4))
    (custom-themed (:foreground yellow :background bg))
    (custom-changed (:foreground blue :background bg))
    (custom-set (:foreground yellow :background bg))
    (custom-modified (:foreground blue :background base4))
    (custom-rogue (:foreground magenta :background base0))
    (custom-invalid (:foreground red :background base3))
    (treesit-explorer-field-name nil)
    (treesit-explorer-anonymous-node (:inherit 'shadow))
    (corfu-popupinfo (:inherit 'corfu-default))
    (corfu-deprecated (:strike-through t :inherit 'shadow))
    (corfu-annotations (:inherit 'completions-annotations))
    (corfu-border (:background base6))
    (corfu-bar (:background base6))
    (corfu-current (:extend t :foreground fg :background base3))
    (corfu-default (:inherit 'tooltip))
    (marginalia-file-priv-rare (:foreground fg))
    (marginalia-file-priv-other (:foreground magenta))
    (marginalia-file-priv-exec (:foreground green))
    (marginalia-file-priv-write (:foreground red))
    (marginalia-file-priv-read (:foreground yellow))
    (marginalia-file-priv-link (:foreground violet))
    (marginalia-file-priv-dir (:foreground blue))
    (marginalia-file-priv-no (:inherit 'shadow))
    (marginalia-file-owner (:inherit 'font-lock-preprocessor-face))
    (marginalia-file-name (:inherit 'marginalia-documentation))
    (marginalia-modified (:inherit 'font-lock-negation-char-face))
    (marginalia-string (:inherit 'font-lock-string-face))
    (marginalia-number (:foreground magenta))
    (marginalia-size (:foreground violet))
    (marginalia-installed (:inherit 'success))
    (marginalia-archive (:inherit 'warning))
    (marginalia-version (:inherit 'marginalia-number))
    (marginalia-date (:inherit 'marginalia-key))
    (marginalia-mode (:inherit 'marginalia-key))
    (marginalia-list (:inherit 'font-lock-constant-face))
    (marginalia-symbol (:inherit 'font-lock-type-face))
    (marginalia-function (:inherit 'font-lock-function-name-face))
    (marginalia-true (:inherit 'font-lock-builtin-face))
    (marginalia-null (:inherit 'font-lock-comment-face))
    (marginalia-value (:inherit 'marginalia-key))
    (marginalia-documentation (:inherit 'font-lock-doc-face))
    (marginalia-off (:inherit 'error))
    (marginalia-on (:inherit 'success))
    (marginalia-lighter (:foreground violet))
    (marginalia-char (:inherit 'marginalia-key))
    (marginalia-type (:inherit 'marginalia-key))
    (marginalia-key (:inherit 'font-lock-keyword-face))
    (vertico-current (:extend t :background base4))
    (vertico-group-separator (:strike-through t :inherit 'shadow))
    (vertico-group-title (:slant 'italic :inherit 'shadow))
    (vertico-multiline (:inherit 'shadow))
    (grep-heading (:inherit 'compilation-info))
    (compilation-column-number (:inherit 'font-lock-comment-face))
    (compilation-line-number (:foreground blue))
    (compilation-mode-line-exit (:inherit 'compilation-info))
    (compilation-mode-line-run (:inherit 'compilation-warning))
    (compilation-mode-line-fail (:inherit 'compilation-error))
    (compilation-info (:inherit 'success))
    (compilation-warning (:slant 'italic :inherit 'warning))
    (compilation-error (:weight 'bold :inherit 'error))
    (comint-highlight-prompt (:inherit 'minibuffer-prompt))
    (comint-highlight-input (:weight 'bold))
    (ansi-color-bright-white (:foreground base8 :background base8))
    (ansi-color-bright-cyan (:foreground cyan :background cyan))
    (ansi-color-bright-magenta (:foreground magenta :background magenta))
    (ansi-color-bright-blue (:foreground blue :background blue))
    (ansi-color-bright-yellow (:foreground yellow :background yellow))
    (ansi-color-bright-green (:foreground green :background green))
    (ansi-color-bright-red (:foreground red :background red))
    (ansi-color-bright-black (:foreground base6 :background base6))
    (ansi-color-white (:foreground fg :background fg))
    (ansi-color-cyan (:foreground cyan :background cyan))
    (ansi-color-magenta (:foreground magenta :background magenta))
    (ansi-color-blue (:foreground blue :background blue))
    (ansi-color-yellow (:foreground yellow :background yellow))
    (ansi-color-green (:foreground green :background green))
    (ansi-color-red (:foreground red :background red))
    (ansi-color-black (:foreground bg :background bg))
    (ansi-color-inverse (:inverse-video t))
    (ansi-color-fast-blink (:box (:line-width -1)))
    (ansi-color-slow-blink (:box (:line-width -1)))
    (ansi-color-underline (:inherit 'underline))
    (ansi-color-italic (:inherit 'italic))
    (ansi-color-faint (:weight 'light))
    (ansi-color-bold (:inherit 'bold))
    (which-key-docstring-face (:inherit 'which-key-note-face))
    (which-key-special-key-face
     (:weight 'bold :inverse-video t :inherit 'which-key-key-face))
    (which-key-group-description-face (:foreground violet))
    (which-key-highlighted-command-face
     (:inherit ('which-key-command-description-face 'highlight)))
    (which-key-local-map-description-face (:foreground magenta))
    (which-key-command-description-face (:foreground blue))
    (which-key-note-face (:inherit 'which-key-separator-face))
    (which-key-separator-face (:inherit 'font-lock-comment-face))
    (which-key-key-face (:foreground green))
    (edmacro-label (:foreground cyan :inherit 'bold))
    (kmacro-menu-marked (:inherit 'warning))
    (kmacro-menu-flagged (:inherit 'error))
    (kmacro-menu-mark (:inherit 'font-lock-constant-face))
    (widget-button-pressed (:foreground red))
    (widget-unselected (:inherit 'widget-inactive))
    (widget-inactive (:inherit 'shadow))
    (widget-single-line-field (:background base3))
    (widget-field (:extend t :box (:line-width -1 :color base4) :background base3))
    (widget-button (:weight 'bold))
    (widget-documentation (:foreground green))
    (package-status-avail-obso (:inherit 'package-status-incompat))
    (package-status-incompat (:inherit 'error))
    (package-status-unsigned (:inherit 'font-lock-warning-face))
    (package-status-dependency (:inherit 'package-status-installed))
    (package-status-from-source (:inherit 'font-lock-negation-char-face))
    (package-status-installed (:inherit 'font-lock-comment-face))
    (package-status-disabled (:inherit 'font-lock-warning-face))
    (package-status-held (:inherit 'font-lock-constant-face))
    (package-status-new (:inherit ('bold 'package-status-available)))
    (package-status-available (:inherit 'default))
    (package-status-external (:inherit 'package-status-built-in))
    (package-status-built-in (:inherit 'font-lock-builtin-face))
    (package-description (:inherit 'default))
    (package-name (:inherit 'link))
    (package-help-section-name (:inherit ('bold 'font-lock-function-name-face)))
    (browse-url-button (:inherit 'link))
    (icon-button
     (:box (:line-width '(3 . -1) :color base3 :style 'flat-button) :foreground
           base0 :background base6 :inherit 'icon))
    (icon (:underline nil))
    (Info-quoted (:inherit 'fixed-pitch-serif))
    (info-index-match (:inherit 'match))
    (info-header-node (:inherit 'info-node))
    (info-header-xref (:inherit 'info-xref))
    (info-xref-visited (:inherit ('link-visited 'info-xref)))
    (info-xref (:inherit 'link))
    (info-menu-star (:foreground orange))
    (info-menu-header (:weight 'bold :inherit 'variable-pitch))
    (info-title-4 (:weight 'bold :inherit 'variable-pitch))
    (info-title-3 (:height 1.2 :inherit 'info-title-4))
    (info-title-2 (:height 1.2 :inherit 'info-title-3))
    (info-title-1 (:height 1.2 :inherit 'info-title-2))
    (info-node (:weight 'bold :slant 'italic :foreground fg))
    (tooltip (:foreground fg :background bg-alt))
    (eldoc-highlight-function-argument (:inherit 'bold))
    (elisp-shorthand-font-lock-face
     (:foreground teal :inherit 'font-lock-keyword-face))
    (vc-ignored-state (:inherit 'vc-state-base))
    (vc-edited-state (:foreground yellow :inherit 'italic))
    (vc-missing-state (:inherit 'vc-state-base))
    (vc-removed-state (:inherit 'vc-state-base))
    (vc-conflict-state (:foreground red))
    (vc-locally-added-state (:foreground blue))
    (vc-locked-state (:inherit 'vc-state-base))
    (vc-needs-update-state (:foreground yellow :weight 'bold))
    (vc-up-to-date-state (:foreground green))
    (vc-state-base nil)
    (buffer-menu-buffer (:weight 'bold))
    (tabulated-list-fake-header (:weight 'bold :underline t :overline t))
    (match (:weight 'bold :foreground green :background base0))
    (query-replace (:inherit 'isearch))
    (tab-bar-tab-ungrouped (:inherit ('shadow 'tab-bar-tab-inactive)))
    (tab-bar-tab-group-inactive (:inherit ('shadow 'tab-bar-tab-inactive)))
    (tab-bar-tab-group-current (:weight 'bold :box nil :inherit 'tab-bar-tab))
    (tab-bar-tab-inactive
     (:box nil :foreground dark-blue :background bg-alt :inherit 'tab-line-tab))
    (tab-bar-tab (:box nil :foreground fg :background bg))
    (file-name-shadow (:inherit 'shadow))
    (isearch-group-2 (:foreground base0 :background orange))
    (isearch-group-1 (:foreground base0 :background blue))
    (lazy-highlight (:weight 'bold :foreground fg :background base5))
    (isearch-fail (:weight 'bold :foreground base0 :background red))
    (isearch (:weight 'bold :foreground base0 :background yellow))
    (mouse-drag-and-drop-region (:inherit 'region))
    (font-lock-misc-punctuation-face (:inherit 'font-lock-punctuation-face))
    (font-lock-delimiter-face (:inherit 'font-lock-punctuation-face))
    (font-lock-bracket-face (:inherit 'font-lock-punctuation-face))
    (font-lock-punctuation-face nil)
    (font-lock-property-use-face (:inherit 'font-lock-property-name-face))
    (font-lock-property-name-face (:inherit 'font-lock-variable-name-face))
    (font-lock-operator-face nil) (font-lock-number-face (:foreground magenta))
    (font-lock-escape-face (:inherit 'font-lock-regexp-grouping-backslash))
    (font-lock-regexp-grouping-construct (:foreground blue :inherit 'bold))
    (font-lock-regexp-grouping-backslash (:foreground blue :inherit 'bold))
    (font-lock-regexp-face (:inherit 'font-lock-string-face))
    (font-lock-preprocessor-face (:foreground blue :inherit 'bold))
    (font-lock-negation-char-face (:foreground blue :inherit 'bold))
    (font-lock-warning-face (:inherit 'warning))
    (font-lock-constant-face (:foreground blue))
    (font-lock-type-face (:foreground teal))
    (font-lock-variable-use-face (:inherit 'font-lock-variable-name-face))
    (font-lock-variable-name-face (:foreground base7))
    (font-lock-function-call-face (:inherit 'font-lock-function-name-face))
    (font-lock-function-name-face (:foreground cyan))
    (font-lock-builtin-face (:foreground blue :weight 'bold))
    (font-lock-keyword-face (:foreground orange :weight 'bold))
    (font-lock-doc-markup-face (:inherit 'font-lock-constant-face))
    (font-lock-doc-face (:foreground base6 :inherit 'font-lock-comment-face))
    (font-lock-string-face (:foreground green))
    (font-lock-comment-delimiter-face (:inherit 'font-lock-comment-face))
    (font-lock-comment-face (:foreground base6))
    (completions-common-part (:foreground cyan))
    (completions-first-difference (:inherit 'bold))
    (completions-highlight (:inherit 'highlight))
    (completions-annotations (:inherit ('italic 'shadow)))
    (completions-group-separator (:strike-through t :inherit 'shadow))
    (completions-group-title (:slant 'italic :inherit 'shadow))
    (blink-matching-paren-offscreen (:foreground green))
    (separator-line (:height 0.1 :background base4))
    (next-error-message (:extend t :inherit 'highlight))
    (next-error (:inherit 'region))
    (confusingly-reordered (:underline (:style 'line :position 3 :color orange)))
    (help-for-help-header (:height 1.26))
    (abbrev-table-name (:inherit 'font-lock-function-name-face))
    (button (:inherit 'link))
    (show-paren-mismatch (:weight 'ultra-bold :foreground base7 :background red))
    (show-paren-match-expression (:inherit 'show-paren-match))
    (show-paren-match (:weight 'ultra-bold :foreground bg :background teal))
    (tty-menu-selected-face (:background orange))
    (tty-menu-disabled-face (:foreground base7 :background base5))
    (tty-menu-enabled-face (:weight 'bold :foreground yellow :background base5))
    (read-multiple-choice-face
     (:weight 'bold :inherit ('help-key-binding 'underline)))
    (success (:foreground green)) (warning (:foreground yellow))
    (error (:foreground red))
    (glyphless-char (:height 0.6))
    (help-key-binding (:foreground orange :background bg :weight 'bold :inherit 'fixed-pitch))
    (help-argument-name (:inherit 'italic))
    (menu (:inverse-video t))
    (tab-line (:box nil :foreground blue :background bg-alt))
    (tab-bar (:box nil :foreground blue :background bg-alt))
    (tool-bar
     (:box (:line-width 1 :style 'released-button) :foreground base0 :background
           base7))
    (mouse nil)
    (cursor (:background orange))
    (border nil)
    (scroll-bar nil)
    (fringe (:foreground teal))
    (minibuffer-prompt (:foreground yellow))
    (child-frame-border nil)
    (internal-border (:background bg))
    (window-divider-last-pixel (:inherit 'window-divider))
    (window-divider-first-pixel (:inherit 'window-divider))
    (window-divider (:inherit 'vertical-border))
    (vertical-border (:foreground bg :background bg))
    (header-line-highlight (:inherit 'mode-line-highlight))
    (header-line (:inherit 'mode-line))
    (mode-line-buffer-id (:weight 'bold))
    (mode-line-emphasis (:foreground blue))
    (mode-line-highlight (:inherit 'highlight))
    (mode-line-inactive
     (:box (:line-width '(6 . 6) :color base3-alt) :foreground base5-alt :background base3-alt :inherit 'mode-line))
    (mode-line-active
     (:box (:line-width '(6 . 6) :color base3) :background base3 :inherit 'mode-line))
    (mode-line
     (:box (:line-width '(6 . 6) :color base3) :foreground base6 :background base3 :height 0.9 :weight 'bold))
    (nobreak-hyphen (:foreground yellow))
    (nobreak-space (:underline t :inherit 'escape-glyph))
    (homoglyph (:foreground teal))
    (escape-glyph (:foreground cyan))
    (fill-column-indicator
     (:weight 'normal :slant 'normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :inherit 'shadow))
    (line-number-minor-tick (:weight 'bold :background base6))
    (line-number-major-tick (:weight 'bold :background base7))
    (line-number-current-line
     (:weight 'normal :foreground yellow))
    (line-number
     (:weight 'normal :foreground base5-alt :inherit 'default))
    (trailing-whitespace (:background red))
    (secondary-selection (:extend t :background base4))
    (region (:extend t :background base4))
    (highlight (:foreground yellow))
    (link-visited (:foreground magenta :inherit 'link))
    (link (:weight 'bold :underline t :foreground blue))
    (shadow (:foreground base5))
    (variable-pitch-text (:height 1.1 :inherit 'variable-pitch))
    (variable-pitch (:family "Noto Sans"))
    (fixed-pitch-serif (:family "Monospace"))
    (fixed-pitch (:family "Monospace"))
    (underline (:underline t))
    (bold-italic (:inherit ('bold 'italic)))
    (italic (:slant 'italic))
    (bold (:weight 'bold))
    (erc-underline-face (:underline t))
    (erc-spoiler-face (:inherit 'default))
    (erc-inverse-face (:inverse-video t))
    (erc-italic-face (:slant 'italic))
    (erc-bold-face (:weight 'bold))
    (erc-command-indicator-face (:inherit ('erc-input-face 'fixed-pitch-serif)))
    (erc-keep-place-indicator-arrow (:foreground green))
    (erc-keep-place-indicator-line (:underline (:color green :style 'line :position 3)))
    (erc-button-nick-default-face (:inherit 'erc-nick-default-face))
    (erc-button (:weight 'bold :foreground cyan :underline (:color cyan :style 'line)))
    (erc-fill-wrap-merge-indicator-face (:foreground base5-alt2))
    (erc-timestamp-face (:weight 'bold :foreground base4))
    (erc-nick-msg-face (:weight 'bold :foreground red))
    (erc-nick-default-face (:weight 'bold))
    (erc-my-nick-face (:weight 'bold :foreground red))
    (erc-information (:inherit 'shadow))
    (erc-error-face (:foreground red))
    (erc-action-face (:weight 'semi-bold))
    (erc-notice-face (:weight 'semi-bold :foreground base5))
    (erc-prompt-face (:weight 'bold :foreground fg :background bg))
    (erc-input-face (:foreground green))
    (erc-header-line (:inherit 'header-line))
    (erc-direct-msg-face (:foreground red))
    (erc-my-nick-prefix-face (:weight 'bold :inherit 'erc-nick-default-face))
    (erc-nick-prefix-face (:weight 'bold :inherit 'erc-nick-default-face))
    (erc-default-face nil)
    (erc-keyword-face (:weight 'bold :foreground green))
    (erc-fool-face (:foreground base5-alt2))
    (erc-pal-face (:weight 'bold :foreground magenta))
    (erc-dangerous-host-face (:foreground orange))
    (erc-current-nick-face (:weight 'bold :foreground red))
    (nerd-icons-dired-dir-face nil)
    (nerd-icons-dsilver (:foreground base5-alt2))
    (nerd-icons-lsilver (:foreground base7))
    (nerd-icons-silver (:foreground base5-alt2))
    (nerd-icons-dpink (:foreground violet))
    (nerd-icons-lpink (:foreground orange))
    (nerd-icons-pink (:foreground magenta))
    (nerd-icons-dcyan (:foreground dark-cyan))
    (nerd-icons-lcyan (:foreground teal))
    (nerd-icons-cyan-alt (:foreground cyan))
    (nerd-icons-cyan (:foreground teal))
    (nerd-icons-dorange (:foreground orange))
    (nerd-icons-lorange (:foreground yellow))
    (nerd-icons-orange (:foreground orange))
    (nerd-icons-dpurple (:foreground base4))
    (nerd-icons-lpurple (:foreground magenta))
    (nerd-icons-purple-alt (:foreground violet))
    (nerd-icons-purple (:foreground magenta))
    (nerd-icons-dmaroon (:foreground base5-alt))
    (nerd-icons-lmaroon (:foreground orange))
    (nerd-icons-maroon (:foreground red))
    (nerd-icons-dblue (:foreground dark-cyan))
    (nerd-icons-lblue (:foreground cyan))
    (nerd-icons-blue-alt (:foreground dark-blue))
    (nerd-icons-blue (:foreground blue))
    (nerd-icons-dyellow (:foreground orange))
    (nerd-icons-lyellow (:foreground yellow))
    (nerd-icons-yellow (:foreground yellow))
    (nerd-icons-dgreen (:foreground green))
    (nerd-icons-lgreen (:foreground green))
    (nerd-icons-green (:foreground green))
    (nerd-icons-red-alt (:foreground red))
    (nerd-icons-dred (:foreground red))
    (nerd-icons-lred (:foreground red))
    (nerd-icons-red (:foreground red))
    (hl-line (:extend t :background base3))
    (elfeed-search-filter-face (:inherit 'mode-line-buffer-id))
    (elfeed-search-unread-count-face (:foreground fg))
    (elfeed-search-last-update-face nil)
    (elfeed-search-tag-face (:foreground yellow))
    (elfeed-search-feed-face (:foreground green))
    (elfeed-search-unread-title-face (:weight 'bold :foreground fg))
    (elfeed-search-title-face (:foreground base5))
    (elfeed-search-date-face (:foreground base5))
    (elfeed-log-debug-level-face (:foreground magenta))
    (elfeed-log-info-level-face (:foreground cyan))
    (elfeed-log-warn-level-face (:foreground yellow))
    (elfeed-log-error-level-face (:foreground orange))
    (elfeed-log-date-face (:inherit 'font-lock-type-face))
    (helpful-heading (:weight 'bold))
    (edebug-disabled-breakpoint (:extend t :background dark-cyan))
    (edebug-enabled-breakpoint (:inherit 'highlight))
    (markdown-header-face-6 (:height 1.0 :inherit 'markdown-header-face))
    (markdown-header-face-5 (:height 1.0 :inherit 'markdown-header-face))
    (markdown-header-face-4 (:height 1.0 :inherit 'markdown-header-face))
    (markdown-header-face-3 (:height 1.0 :inherit 'markdown-header-face))
    (markdown-header-face-2 (:height 1.0 :inherit 'markdown-header-face))
    (markdown-header-face-1 (:height 1.0 :inherit 'markdown-header-face))
    (markdown-header-face (:weight 'bold :inherit ('font-lock-function-name-face)))
    (markdown-highlighting-face (:foreground base0 :background yellow))
    (markdown-html-entity-face (:inherit 'font-lock-variable-name-face))
    (markdown-html-attr-value-face (:inherit 'font-lock-string-face))
    (markdown-html-attr-name-face (:inherit 'font-lock-variable-name-face))
    (markdown-html-tag-delimiter-face (:inherit 'markdown-markup-face))
    (markdown-html-tag-name-face (:inherit 'font-lock-type-face))
    (markdown-hr-face (:inherit 'markdown-markup-face))
    (markdown-highlight-face (:inherit 'highlight))
    (markdown-gfm-checkbox-face (:inherit 'font-lock-builtin-face))
    (markdown-metadata-value-face (:inherit 'font-lock-string-face))
    (markdown-metadata-key-face (:inherit 'font-lock-variable-name-face))
    (markdown-math-face (:inherit 'font-lock-string-face))
    (markdown-comment-face (:inherit 'font-lock-comment-face))
    (markdown-line-break-face (:underline t :inherit 'font-lock-constant-face))
    (markdown-link-title-face (:inherit 'font-lock-comment-face))
    (markdown-plain-url-face (:inherit 'markdown-link-face))
    (markdown-url-face (:inherit 'font-lock-string-face))
    (markdown-footnote-text-face (:inherit 'font-lock-comment-face))
    (markdown-footnote-marker-face (:inherit 'markdown-markup-face))
    (markdown-reference-face (:inherit 'markdown-markup-face))
    (markdown-missing-link-face (:inherit 'font-lock-warning-face))
    (markdown-link-face (:inherit 'link))
    (markdown-language-info-face (:inherit 'font-lock-string-face))
    (markdown-language-keyword-face (:inherit 'font-lock-type-face))
    (markdown-table-face (:inherit ('markdown-code-face)))
    (markdown-pre-face (:inherit ('markdown-code-face 'font-lock-constant-face)))
    (markdown-inline-code-face
     (:inherit ('markdown-code-face 'font-lock-constant-face)))
    (markdown-code-face (:inherit 'fixed-pitch))
    (markdown-blockquote-face (:inherit 'font-lock-doc-face))
    (markdown-list-face (:inherit 'markdown-markup-face))
    (markdown-header-delimiter-face (:inherit 'markdown-markup-face))
    (markdown-header-rule-face (:inherit 'markdown-markup-face))
    (markdown-markup-face (:weight 'normal :slant 'normal :inherit 'shadow))
    (markdown-strike-through-face (:strike-through t))
    (markdown-bold-face (:inherit 'bold))
    (markdown-italic-face (:inherit 'italic))
    (outline-8 (:inherit 'font-lock-string-face))
    (outline-7 (:inherit 'font-lock-builtin-face))
    (outline-6 (:inherit 'font-lock-constant-face))
    (outline-5 (:inherit 'font-lock-type-face))
    (outline-4 (:inherit 'font-lock-comment-face))
    (outline-3 (:inherit 'font-lock-keyword-face))
    (outline-2 (:inherit 'font-lock-variable-name-face))
    (outline-1 (:inherit 'font-lock-function-name-face))
    (envrc-mode-line-none-face (:inherit 'warning))
    (envrc-mode-line-error-face (:inherit 'error))
    (envrc-mode-line-on-face (:inherit 'success))
    (vterm-color-inverse-video (:inherit 'default))
    (vterm-color-underline (:inherit 'default))
    (vterm-color-bright-white (:inherit 'term-color-bright-white))
    (vterm-color-bright-cyan (:inherit 'term-color-bright-cyan))
    (vterm-color-bright-magenta (:inherit 'term-color-bright-magenta))
    (vterm-color-bright-blue (:inherit 'term-color-bright-blue))
    (vterm-color-bright-yellow (:inherit 'term-color-bright-yellow))
    (vterm-color-bright-green (:inherit 'term-color-bright-green))
    (vterm-color-bright-red (:inherit 'term-color-bright-red))
    (vterm-color-bright-black (:inherit 'term-color-bright-black))
    (vterm-color-white (:inherit 'term-color-white))
    (vterm-color-cyan (:inherit 'term-color-cyan))
    (vterm-color-magenta (:inherit 'term-color-magenta))
    (vterm-color-blue (:inherit 'term-color-blue))
    (vterm-color-yellow (:inherit 'term-color-yellow))
    (vterm-color-green (:inherit 'term-color-green))
    (vterm-color-red (:inherit 'term-color-red))
    (vterm-color-black (:inherit 'term-color-black))
    (term-color-bright-white (:inherit 'ansi-color-bright-white))
    (term-color-bright-cyan (:inherit 'ansi-color-bright-cyan))
    (term-color-bright-magenta (:inherit 'ansi-color-bright-magenta))
    (term-color-bright-blue (:inherit 'ansi-color-bright-blue))
    (term-color-bright-yellow (:inherit 'ansi-color-bright-yellow))
    (term-color-bright-green (:inherit 'ansi-color-bright-green))
    (term-color-bright-red (:inherit 'ansi-color-bright-red))
    (term-color-bright-black (:inherit 'ansi-color-bright-black))
    (term-color-white (:inherit 'ansi-color-white))
    (term-color-cyan (:inherit 'ansi-color-cyan))
    (term-color-magenta (:inherit 'ansi-color-magenta))
    (term-color-blue (:inherit 'ansi-color-blue))
    (term-color-yellow (:inherit 'ansi-color-yellow))
    (term-color-green (:inherit 'ansi-color-green))
    (term-color-red (:inherit 'ansi-color-red))
    (term-color-black (:inherit 'ansi-color-black))
    (term-fast-blink (:inherit 'ansi-color-fast-blink))
    (term-slow-blink (:inherit 'ansi-color-slow-blink))
    (term-underline (:inherit 'ansi-color-underline))
    (term-italic (:inherit 'ansi-color-italic))
    (term-faint (:inherit 'ansi-color-faint))
    (term-bold (:inherit 'ansi-color-bold)) (term (:inherit 'default))
    (eglot-parameter-hint-face (:inherit 'eglot-inlay-hint-face))
    (eglot-type-hint-face (:inherit 'eglot-inlay-hint-face))
    (eglot-inlay-hint-face (:height 0.8 :inherit 'shadow))
    (eglot-diagnostic-tag-deprecated-face (:strike-through t :inherit 'shadow))
    (eglot-diagnostic-tag-unnecessary-face (:inherit 'shadow))
    (eglot-mode-line (:weight 'bold :inherit 'font-lock-constant-face))
    (eglot-highlight-symbol-face (:inherit 'bold))
    (flymake-eol-information-face
     (:slant 'italic :box nil :inherit ('flymake-end-of-line-diagnostics-face)))
    (flymake-note-echo-at-eol
     (:inherit ('flymake-end-of-line-diagnostics-face 'compilation-info)))
    (flymake-warning-echo-at-eol
     (:inherit ('flymake-end-of-line-diagnostics-face 'compilation-warning)))
    (flymake-error-echo-at-eol
     (:inherit ('flymake-end-of-line-diagnostics-face 'compilation-error)))
    (flymake-end-of-line-diagnostics-face (:height 0.8))
    (flymake-note-echo (:inherit 'compilation-info))
    (flymake-warning-echo (:inherit 'compilation-warning))
    (flymake-error-echo (:inherit 'compilation-error))
    (flymake-note (:underline (:style 'line :position 3 :color green)))
    (flymake-warning (:underline (:style 'line :position 3 :color cyan)))
    (flymake-error (:underline (:style 'line :position 3 :color orange)))
    (ert-test-result-unexpected (:background red))
    (ert-test-result-expected (:background green))
    (c-nonbreakable-space-face (:foreground bg :background fg :inherit 'warning))
    (c-annotation-face (:inherit 'font-lock-constant-face))
    (ediff-odd-diff-Ancestor (:extend t :background base5-alt))
    (ediff-odd-diff-C (:extend t :background base5-alt))
    (ediff-odd-diff-B (:extend t :background base6))
    (ediff-odd-diff-A (:extend t :background base5-alt))
    (ediff-even-diff-Ancestor (:extend t :background base5-alt))
    (ediff-even-diff-C (:extend t :background base6))
    (ediff-even-diff-B (:extend t :background base5-alt))
    (ediff-even-diff-A (:extend t :background base6))
    (ediff-fine-diff-Ancestor (:background dark-cyan))
    (ediff-fine-diff-C (:background green))
    (ediff-fine-diff-B (:background green))
    (ediff-fine-diff-A (:background red))
    (ediff-current-diff-Ancestor (:extend t :background base2))
    (ediff-current-diff-C (:extend t :background green))
    (ediff-current-diff-B (:extend t :background dark-cyan))
    (ediff-current-diff-A (:extend t :background base1))
    (pulse-highlight-face (:extend nil :background green))
    (pulse-highlight-start-face (:background green))
    (doc-view-svg-face (:foreground base0 :background fg :inherit 'default))
    (sh-escaped-newline (:inherit 'font-lock-string-face))
    (sh-quoted-exec (:foreground orange))
    (sh-heredoc (:weight 'bold :foreground yellow))
    (org-mode-line-clock-overrun (:background orange :inherit 'mode-line))
    (org-mode-line-clock (:inherit 'mode-line))
    (org-tag-group (:inherit 'org-tag))
    (org-macro (:inherit 'org-latex-and-related))
    (org-latex-and-related (:foreground yellow))
    (org-agenda-calendar-sexp (:inherit 'default))
    (org-agenda-calendar-event (:inherit 'default))
    (org-agenda-calendar-daterange (:inherit 'default))
    (org-agenda-diary (:inherit 'default))
    (org-agenda-current-time (:inherit 'org-time-grid))
    (org-time-grid (:foreground yellow))
    (org-agenda-filter-regexp (:inherit 'mode-line))
    (org-agenda-filter-effort (:inherit 'mode-line))
    (org-agenda-filter-category (:inherit 'mode-line))
    (org-agenda-filter-tags (:inherit 'mode-line))
    (org-agenda-restriction-lock (:background base0))
    (org-upcoming-distant-deadline (:inherit 'org-default))
    (org-upcoming-deadline (:foreground orange))
    (org-imminent-deadline (:inherit 'org-warning))
    (org-scheduled-previously (:foreground orange))
    (org-agenda-dimmed-todo-face (:foreground base5-alt2))
    (org-scheduled-today (:foreground green))
    (org-scheduled (:foreground green))
    (org-agenda-date-weekend (:weight 'bold :inherit 'org-agenda-date))
    (org-agenda-clocking (:inherit 'secondary-selection))
    (org-agenda-date-weekend-today (:inherit 'org-agenda-date-today))
    (org-agenda-date-today (:weight 'bold :slant 'italic :inherit 'org-agenda-date))
    (org-agenda-date (:inherit 'org-agenda-structure))
    (org-agenda-structure-filter (:inherit ('org-warning 'org-agenda-structure)))
    (org-agenda-structure-secondary (:inherit 'org-agenda-structure))
    (org-agenda-structure (:foreground cyan))
    (org-clock-overlay (:foreground fg :background dark-cyan))
    (org-verse (:inherit 'org-block))
    (org-quote (:inherit 'org-block))
    (org-verbatim (:inherit 'shadow))
    (org-inline-src-block (:inherit 'org-block))
    (org-block-end-line (:extend t :inherit 'org-block-begin-line))
    (org-block-begin-line (:extend t :inherit 'org-meta-line))
    (org-block (:extend t :background base3 :foreground green))
    (org-document-info-keyword (:inherit 'shadow))
    (org-document-info (:foreground teal))
    (org-document-title (:weight 'bold :foreground teal))
    (org-meta-line (:inherit 'font-lock-comment-face))
    (org-code (:inherit 'shadow))
    (org-formula (:foreground orange))
    (org-table-header (:foreground base0 :background base7 :inherit 'org-table))
    (org-table-row (:inherit 'org-table))
    (org-table (:foreground cyan))
    (org-checkbox-statistics-done (:inherit 'org-done))
    (org-checkbox-statistics-todo (:inherit 'org-todo))
    (org-checkbox (:inherit 'bold))
    (org-priority (:inherit 'font-lock-keyword-face))
    (org-headline-done (:foreground orange))
    (org-headline-todo (:foreground magenta))
    (org-agenda-done (:foreground green))
    (org-done (:weight 'bold :foreground green))
    (org-todo (:weight 'bold :foreground magenta))
    (org-list-dt (:weight 'bold))
    (org-tag (:weight 'bold)) (org-sexp-date (:foreground teal))
    (org-date-selected (:inverse-video t :foreground magenta))
    (org-date (:underline t :foreground teal))
    (org-target (:underline t))
    (org-ellipsis (:underline t :foreground yellow))
    (org-footnote (:underline t :foreground teal))
    (org-link (:inherit 'link))
    (org-cite-key (:inherit 'link))
    (org-cite (:inherit 'link))
    (org-archived (:inherit 'shadow))
    (org-warning (:inherit 'font-lock-warning-face))
    (org-agenda-column-dateline (:inherit 'org-column))
    (org-column-title (:weight 'bold :underline t :background base3-alt))
    (org-column
     (:weight 'normal :slant 'normal :underline nil :strike-through nil :background
              base3-alt))
    (org-property-value (:inherit 'default)) (org-drawer (:foreground cyan))
    (org-special-keyword (:inherit 'font-lock-keyword-face))
    (org-level-8 (:extend nil :inherit 'outline-8))
    (org-level-7 (:extend nil :inherit 'outline-7))
    (org-level-6 (:extend nil :inherit 'outline-6))
    (org-level-5 (:extend nil :inherit 'outline-5))
    (org-level-4 (:extend nil :inherit 'outline-4))
    (org-level-3 (:extend nil :inherit 'outline-3))
    (org-level-2 (:extend nil :inherit 'outline-2))
    (org-level-1 (:extend nil :inherit 'outline-1))
    (org-dispatcher-highlight (:weight 'bold :foreground yellow :background bg-alt))
    (org-hide (:foreground bg))
    (org-default (:inherit 'default))
    (calendar-month-header (:inherit 'font-lock-function-name-face))
    (calendar-weekend-header (:inherit 'font-lock-comment-face))
    (calendar-weekday-header (:inherit 'font-lock-constant-face))
    (holiday (:background red))
    (diary (:foreground yellow))
    (calendar-today (:underline t))
    (ibuffer-locked-buffer (:foreground orange))
    (debbugs-gnu-title (:height 1.2 :weight 'bold))
    (debbugs-gnu-marked-stale (:slant 'italic :inherit 'debbugs-gnu-marked))
    (debbugs-gnu-marked (:background base6))
    (debbugs-gnu-tagged (:foreground orange))
    (debbugs-gnu-forwarded (:foreground yellow))
    (debbugs-gnu-done (:foreground base6))
    (debbugs-gnu-pending (:foreground base2))
    (debbugs-gnu-stale-5 (:foreground yellow))
    (debbugs-gnu-stale-4 (:foreground yellow))
    (debbugs-gnu-stale-3 (:foreground yellow))
    (debbugs-gnu-stale-2 (:foreground yellow))
    (debbugs-gnu-stale-1 (:foreground yellow))
    (debbugs-gnu-handled (:foreground green))
    (debbugs-gnu-new (:foreground orange))
    (debbugs-gnu-archived (:inverse-video t))
    (dictionary-reference-face (:underline t))
    (dictionary-button-face (:weight 'bold))
    (dictionary-word-entry-face (:height 1.2 :weight 'bold))
    (dictionary-word-definition-face (:foreground fg-alt))
    (tab-bar-tab-highlight
     (:box (:line-width 1 :style 'released-button) :foreground base0 :background
           fg-alt))
    (embark-selected (:inherit 'match))
    (embark-collect-annotation (:inherit 'completions-annotations))
    (embark-collect-group-separator
     (:slant 'italic :strike-through t :inherit 'shadow))
    (embark-collect-group-title (:slant 'italic :inherit 'shadow))
    (embark-collect-candidate (:inherit 'default))
    (embark-verbose-indicator-shadowed (:inherit 'shadow))
    (embark-verbose-indicator-title (:height 1.1 :weight 'bold))
    (embark-verbose-indicator-documentation (:inherit 'completions-annotations))
    (embark-target (:inherit 'highlight))
    (embark-keymap (:slant 'italic))
    (embark-keybinding (:inherit 'success))
    (embark-keybinding-repeat (:inherit 'font-lock-builtin-face))
    (texinfo-heading (:inherit 'font-lock-function-name-face))
    (rectangle-preview (:inherit 'region))
    (hl-line-nonselected (:extend t :inherit 'hl-line))
    (forge-suffix-implied (:weight 'normal :inherit 'transient-value))
    (forge-suffix-active-and-implied (:weight 'semibold :inherit 'transient-value))
    (forge-suffix-active (:weight 'bold :inherit 'transient-value))
    (forge-post-date (:inherit 'italic))
    (forge-post-author (:inherit 'bold))
    (forge-topic-label
     (:box (:line-width 1 :style 'released-button) :inherit
           'secondary-selection))
    (forge-pullreq-draft (:inherit 'highlight))
    (forge-pullreq-rejected (:strike-through t :foreground dark-blue))
    (forge-pullreq-merged (:foreground dark-blue))
    (forge-pullreq-open (:foreground green))
    (forge-issue-expunged (:strike-through t :inherit 'forge-dimmed))
    (forge-issue-completed (:inherit 'forge-dimmed))
    (forge-issue-open nil)
    (forge-discussion-expunged
     (:slant 'italic :strike-through t :inherit 'forge-dimmed))
    (forge-discussion-completed (:slant 'italic :inherit 'forge-dimmed))
    (forge-discussion-open (:slant 'italic))
    (forge-topic-done nil)
    (forge-topic-pending (:weight 'bold))
    (forge-topic-unread (:weight 'bold :box (:line-width 1 :style nil)))
    (forge-topic-slug-unread (:weight 'bold))
    (forge-topic-slug-saved (:foreground yellow))
    (forge-topic-slug-expunged (:strike-through t :inherit 'forge-dimmed))
    (forge-topic-slug-realized (:inherit 'forge-dimmed))
    (forge-topic-slug-open (:inherit 'forge-dimmed))
    (forge-discussion-answer-heading (:inherit 'magit-diff-added))
    (forge-topic-header-line (:foreground 'reset :inherit 'magit-header-line))
    (forge-dimmed (:foreground base6))
    (eieio-custom-slot-tag-face (:foreground cyan))
    (magit-diff-conflict-heading-highlight
     (:inherit 'magit-diff-hunk-heading-highlight))
    (smerge-refine-shadow-cursor (:box (:line-width 2)))
    (magit-left-margin (:inherit 'default))
    (llama-deleted-argument (:box (:line-width 1 :color orange :style nil)))
    (llama-optional-argument (:inherit 'font-lock-type-face))
    (llama-mandatory-argument (:inherit 'font-lock-variable-use-face))
    (llama-llama-macro (:inherit 'font-lock-keyword-face))
    (llama-\#\#-macro (:inherit 'font-lock-function-call-face))
    (edit-indirect-edited-region (:inherit 'secondary-selection))
    (guix-devel-gexp-symbol (:inherit 'font-lock-keyword-face))
    (guix-devel-modify-phases-keyword (:inherit 'font-lock-preprocessor-face))
    (ffap (:inherit 'highlight))
    (guix-operation-option-key (:inherit 'font-lock-warning-face))
    (bui-info-param-title (:inherit 'font-lock-type-face))
    (bui-info-heading (:height 1.2 :weight 'bold :inherit 'variable-pitch))
    (bui-hint-key (:inherit 'font-lock-warning-face))
    (bui-history-button (:inherit 'button))
    (bui-action-button-mouse (:inherit 'custom-button-mouse))
    (bui-action-button (:inherit 'custom-button))
    (bui-url (:inherit 'link))
    (bui-file-name (:inherit 'link))
    (bui-time (:inherit 'font-lock-constant-face))
    (guix-false (:weight 'bold))
    (guix-true (:weight 'bold :foreground green))
    (geiser-font-lock-xref-header (:weight 'bold))
    (geiser-font-lock-xref-link (:underline t :foreground teal))
    (transient-key-stack (:foreground red :inherit 'transient-key))
    (transient-key-recurse (:foreground blue :inherit 'transient-key))
    (transient-inapt-argument (:weight 'bold :inherit 'shadow))
    (geiser-font-lock-repl-prompt (:inherit 'minibuffer-prompt))
    (geiser-font-lock-repl-output (:foreground orange))
    (geiser-font-lock-repl-input (:weight 'bold))
    (geiser-font-lock-image-button (:inherit 'link))
    (geiser-font-lock-doc-button (:inherit 'link))
    (geiser-font-lock-doc-link (:underline t :foreground teal))
    (geiser-font-lock-doc-title (:weight 'bold))
    (geiser-font-lock-autodoc-identifier (:foreground cyan))
    (geiser-font-lock-autodoc-current-arg (:foreground yellow))
    (geiser-font-lock-error-link (:underline t :foreground teal))
    (diff-hl-reference-change (:inherit 'diff-hl-change))
    (diff-hl-reference-delete (:inherit 'diff-hl-delete))
    (diff-hl-reference-insert (:inherit 'diff-hl-insert))
    (package-mode-line-new (:inherit 'package-status-new))
    (package-mode-line-to-upgrade (:inherit 'bold))
    (package-mode-line-installed (:inherit 'package-status-installed))
    (package-mode-line-total nil)
    (package-mark-delete-line (:extend t :background red))
    (package-mark-install-line (:extend t :background green))
    (minibuffer-nonselected (:weight 'heavy :foreground bg :background red))
    (whitespace-page-delimiter
     (:height 0.1 :underline (:color 'foreground-color :style 'double-line) :extend t :inherit 'shadow))
    (whitespace-space-after-tab (:foreground red :background yellow))
    (whitespace-empty (:extend t :foreground red :background yellow))
    (whitespace-missing-newline-at-eof (:foreground base0 :background yellow))
    (whitespace-big-indent (:foreground red :background orange))
    (whitespace-indentation (:foreground red :background yellow))
    (whitespace-space-before-tab (:foreground red :background orange))
    (whitespace-line (:foreground magenta :background bg-alt))
    (whitespace-trailing (:weight 'bold :foreground yellow :background orange))
    (whitespace-newline (:weight 'normal :foreground base6))
    (whitespace-tab (:foreground base6 :background base3-alt))
    (whitespace-hspace (:foreground base6 :background base3-alt))
    (whitespace-space (:foreground base6 :background bg-alt))
    (yas--field-debug-face nil)
    (yas-field-highlight-face (:inherit 'region)))))


(provide 'nord-theme)
;;; nord-theme.el ends here
;; Note: emacs 31 change pp to pp-to-string
;; (autothemer-generate-templates)
